global:
  resolve_timeout: 5m
  smtp_smarthost: '__SMTP_SMARTHOST__'
  smtp_from: '__SMTP_FROM__'
  smtp_auth_username: '__SMTP_AUTH_USERNAME__'
  smtp_auth_password: '__SMTP_AUTH_PASSWORD__'
  smtp_require_tls: __SMTP_REQUIRE_TLS__
  
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'admin@auto-rentals.com'
        send_resolved: true
        headers:
          subject: '{{ .Status | toUpper }} - [{{ .CommonLabels.severity }}] {{ .CommonLabels.alertname }}'
