global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:4000"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:4001"]

  - job_name: "vehicle-service"
    static_configs:
      - targets: ["vehicle-service:4002"]

  - job_name: "booking-service"
    static_configs:
      - targets: ["booking-service:4003"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:4004"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:4005"]

  - job_name: "review-service"
    static_configs:
      - targets: ["review-service:4006"]

  - job_name: "admin-service"
    static_configs:
      - targets: ["admin-service:4007"]
